%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/galactic/.*$
%global __requires_exclude_from ^/opt/ros/galactic/.*$

Name:           ros-galactic-micro-ros-diagnostic-bridge
Version:        0.3.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS micro_ros_diagnostic_bridge package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-galactic-diagnostic-msgs
Requires:       ros-galactic-micro-ros-diagnostic-msgs
Requires:       ros-galactic-rclcpp
Requires:       ros-galactic-ros-workspace
BuildRequires:  ros-galactic-ament-cmake-gtest
BuildRequires:  ros-galactic-ament-cmake-ros
BuildRequires:  ros-galactic-ament-lint-auto
BuildRequires:  ros-galactic-ament-lint-common
BuildRequires:  ros-galactic-diagnostic-msgs
BuildRequires:  ros-galactic-micro-ros-diagnostic-msgs
BuildRequires:  ros-galactic-osrf-testing-tools-cpp
BuildRequires:  ros-galactic-rclcpp
BuildRequires:  ros-galactic-ros-environment
BuildRequires:  ros-galactic-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Translates micro-ROS diagnostic messages to vanilla ROS 2 diagnostic messages.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/galactic" \
    -DAMENT_PREFIX_PATH="/opt/ros/galactic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/galactic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/galactic

%changelog
* Tue Feb 01 2022 Bartolome Jimenez Vera <bjv@capra.ooo> - 0.3.0-1
- Autogenerated by Bloom

* Thu Nov 04 2021 Arne Nordmann <arne.nordmann@de.bosch.com> - 0.2.0-4
- Autogenerated by Bloom

* Tue Nov 02 2021 Arne Nordmann <arne.nordmann@de.bosch.com> - 0.2.0-3
- Autogenerated by Bloom

* Thu Oct 28 2021 Arne Nordmann <arne.nordmann@de.bosch.com> - 0.2.0-2
- Autogenerated by Bloom

* Thu Oct 28 2021 Arne Nordmann <arne.nordmann@de.bosch.com> - 0.2.0-1
- Autogenerated by Bloom

