# bridge lookup table
---

hardware_ids:
  ros__parameters:
    1001: esp32_01
    998: esp32_foo
    42: esp32_bar

updaters:
  ros__parameters:
    0:
      name: "google.com checker"
      description: "Periodically checks the website google.com for availability."
      keys:
        42:
          name: "return code"
          values:
            200: "ok"
            404: "not found"
            500: "server error"
    17:
      name: "Processor info"
      description: "Measuring processor temperature and load."
      keys:
        0:
          name: "temp"
        1:
          name: "load"
